root_folder = "/home/"
old_data_directory = root_folder+"data/raw/"
new_data_directory = root_folder+"data/new/"
db_path = root_folder+"database/"
db_file_name = "feature_store_v01.db"
date_columns = ['registration_init_time','transaction_date_min','transaction_date_max','membership_expire_date_max','last_login']
ml_flow_model_path = "runs:/09e49916ff5243119e807062a8c4aff1/models"
run_on = "new" #"old"
append=False
date_transformation = False
start_date = '2017-03-01'
end_date = '2017-03-31'
drfit_db_name = "drift_db_name.db"
